[package]
name = "zkHashMatchGuest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.0", default-features = false, features = ['std'] }
sha2 ="0.9.9"
hex = "0.4" 